---
- name: "[PostgreSQL] - PostgreSQL packages are installed"
  package:
    name: "{{ pg_deps }}"
    state: "present"
  vars:
    pg_deps:
      - "postgresql"
      - "php{{ php_ver }}-pgsql"
      - "python{{ '3' if ansible_python.version.major == 3 else '' }}-psycopg2"

- name: "[PostgreSQL] - generate owncloud role password."
  set_fact: owncloud_db_pwd="{{ lookup( 'password', 'owncloud_instances/'+ owncloud_instance_name +'/pgsql_nc.pwd' ) }}"
  when: owncloud_db_pwd is not defined

- name: "[PostgreSQL] - owncloud role is created."
  postgresql_user:
    name: "{{ owncloud_db_admin }}"
    password: "{{ owncloud_db_pwd }}"
    encrypted: yes
    state: present
    role_attr_flags: CREATEDB
  become_user: postgres
  become: yes

- name: "[PostgreSQL] - owncloud database is created."
  postgresql_db:
    name: "{{ owncloud_db_name }}"
    state: present
    owner: "{{ owncloud_db_admin }}"
  become_user: postgres
  become: yes
