---
- name: "[OC-DL] - Unzip is installed"
  package: name=unzip state=present
  when: owncloud_archive_format == "zip"

- name: "[OC-DL] - bunzip2 is installed"
  package: name=bzip2 state=present
  when: owncloud_archive_format == "tar.bz2"

- name: you must specify the major version
  assert:
    that: owncloud_version_major is defined
  when: owncloud_full_url is defined

#- name: "[OC-DL] - Create webroot folder"
#  file:
#    path: "{{ owncloud_webroot }}"
#    recurese: yes
#    state: directory

- name: "[OC-DL] - Create and set directory ownership & permissions for the webroot folder"
  file:
    path: "{{ owncloud_webroot }}"
    mode: "u=rwX,g=rX,o-rwx"
    recurse: yes
    state: directory
    owner: "{{ owncloud_websrv_user }}"
    group: "{{ owncloud_websrv_group }}"

- block:
  - name: "Download & extract Owncloud to /tmp."
    unarchive:
      copy: no
      src: "{{ owncloud_full_url | default(owncloud_calculated_url) }}"
      dest: "/tmp/"
    vars:
      owncloud_calculated_url: "{{ owncloud_repository }}/{{ owncloud_channel_path[owncloud_version_channel] }}/{{ owncloud_calculated_file }}"
      owncloud_calculated_file: "{{ [owncloud_dl_file_name[owncloud_version_channel], owncloud_archive_format]|join('.') }}"

  - name: "[OC-DL] - Move extracted files to {{ owncloud_webroot }}."
    command: "cp -r /tmp/owncloud/. {{ owncloud_webroot }}/"

  - name: "[OC-DL] - Remove owncloud archive files"
    file: path=/tmp/owncloud state=absent
