---
- name: define private certificate path
  set_fact: owncloud_tls_cert_file="/etc/ssl/{{ owncloud_instance_name }}.crt"
- name: define private key path
  set_fact: owncloud_tls_cert_key_file="/etc/ssl/{{ owncloud_instance_name }}.key"
- name: "[selfsigned TLS] - create self-signed SSL cert"
  command: >
    openssl req -new -nodes -x509
    -subj "/C=US/ST=Oregon/L=Portland/O=IT/CN=${hostname --fqdn}"
    -days 365
    -keyout {{ owncloud_tls_cert_key_file }}
    -out {{ owncloud_tls_cert_file }}
    -extensions v3_ca
  args:
    creates: "{{ owncloud_tls_cert_key_file }}"

- name: "[selfsigned TLS] - check TLS certificate permissions"
  file:
    path: "{{ owncloud_tls_cert_file }}"
    mode: 0644
    group: "{{ owncloud_websrv_group }}"

- name: "[selfsigned TLS] - check TLS key permissions"
  file:
    path: "{{ owncloud_tls_cert_key_file }}"
    mode: 0640
    group: "{{ owncloud_websrv_group }}"
