---
- name: define certificate path
  set_fact: owncloud_tls_cert_file="{{ owncloud_tls_cert }}"
- name: define key path
  set_fact: owncloud_tls_cert_key_file="{{ owncloud_tls_cert_key }}"
- name: define certificate chain  path
  set_fact: owncloud_tls_cert_chain_file="{{ owncloud_tls_cert_chain }}"
  when: owncloud_tls_cert_chain is defined
# - name: "[INSTALLED TLS] - check TLS certificate permissions"
  # file:
    # path: "{{ owncloud_tls_cert_file }}"
    # mode: 0644
    # group: "{{ owncloud_websrv_group }}"

# - name: "[INSTALLED TLS] - check TLS key permissions"
  # file:
    # path: "{{ owncloud_tls_cert_key_file }}"
    # mode: 0640
    # group: "{{ owncloud_websrv_group }}"
